# Generated by Django 4.0.6 on 2022-11-24 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pe', models.FloatField(blank=True)),
                ('Fpe', models.FloatField(blank=True)),
                ('pb', models.FloatField(blank=True)),
                ('eps', models.FloatField(blank=True)),
                ('roe', models.FloatField(blank=True)),
                ('debt', models.FloatField(blank=True)),
                ('divs', models.IntegerField(blank=True)),
                ('targetPrice', models.IntegerField(blank=True)),
                ('recom', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ManyToManyField(blank=True, to='stocks.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='MyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myPrice', models.IntegerField(blank=True)),
                ('quant', models.IntegerField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks')),
            ],
        ),
    ]
