# Generated by Django 4.0.6 on 2022-11-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocks_portfolio_myprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='Fpe',
            new_name='fpe',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='eps',
            new_name='profitMargins',
        ),
    ]
