# Generated by Django 4.0.6 on 2022-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_fpe_stocks_fpe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprice',
            name='myPrice',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
