# Generated by Django 4.0.6 on 2022-12-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_portfolio_profit_alter_stocks_targetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='day',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
