# Generated by Django 4.0.6 on 2022-12-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stocks_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='debt',
        ),
    ]
