# Generated by Django 4.0.6 on 2022-12-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_stocks_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='debt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='day',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='divs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='fpe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='pe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='profitMargins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='recom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='roe',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='targetPrice',
            field=models.FloatField(null=True),
        ),
    ]
