# Generated by Django 4.0.6 on 2023-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
