# Generated by Django 4.0.6 on 2023-01-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_history_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='MyPriceHist',
            field=models.FloatField(default=0),
        ),
    ]
