# Generated by Django 4.0.6 on 2023-01-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_history_mypricehist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='desc',
            field=models.CharField(default='None', max_length=700, null=True),
        ),
    ]
