# Generated by Django 4.0.6 on 2023-01-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stocks_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='note',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks'),
        ),
    ]
