# Generated by Django 4.0.6 on 2023-01-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_history_note_alter_history_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='desc',
            field=models.TextField(default='None', max_length=1000, null=True),
        ),
    ]
