# Generated by Django 4.2.1 on 2023-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_stocks_day_alter_stocks_debt_alter_stocks_divs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
