# Generated by Django 4.2.1 on 2023-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_stocks_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='debt',
            new_name='avPr200',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='desc',
            field=models.TextField(default='None', max_length=1500, null=True),
        ),
    ]
