# Generated by Django 4.2.1 on 2023-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_stocks_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='divs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
