# Generated by Django 4.2.1 on 2023-07-21 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_stocks_debt_alter_stocks_divs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='updateTime',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 18), null=True),
        ),
    ]
