# Generated by Django 4.2.1 on 2023-07-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_stocks_updatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='avPr200',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='divs',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='fpe',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='pb',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='profitMargins',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='recom',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='roe',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='targetPrice',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='updateTime',
        ),
    ]
